# Generated by Django 4.2.10 on 2024-02-16 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productDescription', models.CharField(max_length=100)),
                ('productInStock', models.BooleanField(default=True)),
                ('productAmount', models.FloatField()),
                ('productDiscount', models.FloatField(blank=True, null=True)),
                ('producImageUrl', models.URLField(blank=True)),
                ('productCategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productCategory', to='MyEcartDB.categorytable')),
            ],
        ),
    ]
