# Generated by Django 4.2.10 on 2024-02-16 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyEcartDB', '0002_alter_productstable_productdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytable',
            name='categoryImageUrl',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='SpecialOffersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialOffersName', models.CharField(max_length=100)),
                ('specialOffersDescription', models.TextField(null=True)),
                ('productInStock', models.BooleanField(default=True)),
                ('productAmount', models.FloatField()),
                ('productDiscount', models.FloatField(blank=True, null=True)),
                ('specialOffersImageUrl', models.URLField(blank=True)),
                ('specialOffersCategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specialOffersCategory', to='MyEcartDB.categorytable')),
            ],
        ),
    ]
