# Generated by Django 4.2.10 on 2024-02-18 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyEcartDB', '0003_categorytable_categoryimageurl_specialofferstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImagesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primaryImage', models.URLField(blank=True)),
                ('secondImage', models.URLField(blank=True)),
                ('thirdImage', models.URLField(blank=True)),
                ('fourthImage', models.URLField(blank=True)),
                ('fifthImage', models.URLField(blank=True)),
                ('productName', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MyEcartDB.productstable')),
            ],
        ),
    ]
