# Generated by Django 4.2.10 on 2024-02-18 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyEcartDB', '0004_productimagestable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimagestable',
            name='productName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productDetails', to='MyEcartDB.productstable'),
        ),
    ]
