# Generated by Django 4.2.10 on 2024-02-18 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyEcartDB', '0006_alter_productstable_productcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstable',
            name='productCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productCategory', to='MyEcartDB.categorytable'),
        ),
        migrations.AlterField(
            model_name='specialofferstable',
            name='specialOffersCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='specialOffersCategory', to='MyEcartDB.categorytable'),
        ),
    ]
